"""add_unique_constraints_for_upsert

Revision ID: 2ce07b737b30
Revises: 9d409c54bac0
Create Date: 2026-05-18 13:11:45.804611

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ce07b737b30"
down_revision: str | Sequence[str] | None = "9d409c54bac0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "exercise", ["name"])
    op.create_unique_constraint(None, "routine", ["name"])
    op.create_unique_constraint(None, "set", ["workout_exercise_id", "set_index"])
    op.create_unique_constraint(None, "workout", ["routine_id", "start", "end"])
    op.create_unique_constraint(None, "workout_exercise", ["workout_id", "exercise_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "workout_exercise_workout_id_exercise_id_key", "workout_exercise", type_="unique"
    )
    op.drop_constraint("workout_routine_id_start_end_key", "workout", type_="unique")
    op.drop_constraint("set_workout_exercise_id_set_index_key", "set", type_="unique")
    op.drop_constraint("routine_name_key", "routine", type_="unique")
    op.drop_constraint("exercise_name_key", "exercise", type_="unique")
    # ### end Alembic commands ###
