"""add distance_km, duration_seconds, make weight and reps nullable

Revision ID: b42ad313b006
Revises: 2ce07b737b30
Create Date: 2026-05-22 21:58:07.963082

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b42ad313b006"
down_revision: str | Sequence[str] | None = "2ce07b737b30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("set", sa.Column("distance_km", sa.Float(), nullable=True))
    op.add_column("set", sa.Column("duration_seconds", sa.Float(), nullable=True))
    op.alter_column("set", "reps", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("set", "weight", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "set", "weight", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column("set", "reps", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("set", "duration_seconds")
    op.drop_column("set", "distance_km")
    # ### end Alembic commands ###
