"""add sync_state and workout fields

Revision ID: f300f63fc4a0
Revises: b42ad313b006
Create Date: 2026-05-23 10:53:11.586574

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f300f63fc4a0"
down_revision: str | Sequence[str] | None = "b42ad313b006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("workout", sa.Column("title", sa.String(), nullable=True))
    op.add_column("workout", sa.Column("description", sa.String(), nullable=True))
    op.add_column("workout", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout", "updated_at")
    op.drop_column("workout", "description")
    op.drop_column("workout", "title")
    op.drop_table("sync_state")
    # ### end Alembic commands ###
